name: zzznotes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

assets:
  - assets/icon

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_staggered_grid_view: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1
  rename_app: ^1.6.2
  shared_preferences: ^2.5.1

dev_dependencies:
  build_runner: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
